env:
  path: ./instances/eternity_E.txt
  reward_type: win_ratio

model:
  embedding_dim: 64
  n_layers: 8

reinforce:
  learning_rate: 5.0e-4
  gamma: 0.99
  n_batches: 4000
  batch_size: 10
  model_path: ./logs/eternity_E-supervised-model.pt
  # model_path: ""

supervised:
  learning_rate: 1.0e-3
  batch_size: 128
  epoch_size: 20000
  n_epochs: 10
  test_size: 0.2

data_generation:
  n_samples: 10000

seed: 0
device: auto
group: eternity_E
