env:
  path: ./instances/eternity_trivial_A.txt
  reward_type: win_ratio

model:
  embedding_dim: 12
  n_layers: 4

training:
  learning_rate: 1.0e-3
  gamma: 0.99
  n_batches: 2000
  batch_size: 50

supervised:
  learning_rate: 1.0e-2
  batch_size: 128
  epoch_size: 10000
  n_epochs: 10
  test_size: 0.2

data_generation:
  n_samples: 10000

seed: 0
