env:
  path: ./instances/eternity_trivial_A.txt
  reward_type: win_ratio

model:
  embedding_dim: 8
  n_layers: 2

training:
  learning_rate: 1.0e-3
  gamma: 0.5
  n_batches: 2000
  batch_size: 50
  use_standardized_returns: True
