env:
  path: ./instances/eternity_trivial_A.txt
  reward_type: win_ratio
model:
  embedding_dim: 12
  n_layers: 4
reinforce:
  learning_rate: 1.0e-3
  gamma: 0.99
  n_batches: 2000
  batch_size: 200
supervised:
  learning_rate: 5.0e-3
  batch_size: 128
  epoch_size: 10000
  n_epochs: 100
  test_size: 0.2
data_generation:
  n_samples: 100000
seed: 0
device: auto
